### ISSUE TITLE
PER > Incident Information

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#9]
Remove warning message (we no longer need this now that you can update a PER while it is "in progress")  -- Please take care to select the correct incident type as this selection will populate the related report fields. For this reason, incident type will not be editable after report submission.

**Comment by lbtran** [comment]
Note: let's make incident type remain required (thanks for building that out).

**Comment by gabycostales** [comment]
Ok - and so I should let them change the incident type of an "in progress" report at any time/step?
 
Them doing so is technically a big deal because the app would have to wipe the data they had filled out already for fields dependent on the previous incident type (which is majority of them). I could have dialog box pop up asking them if they are sure they want to do this because they would lose all the previous progress etc though.

**Comment by lbtran** [comment]
oh because of how the database is set up and all the conditional fields based on Incident Type, right? ok then, maybe we should leave this. Let's update the message that displays as follows **and** do what you said re: pop up confirming switching type which will lose previous progress. 

"Please take care to select the correct incident type as this selection will populate the related report fields. If you do change the incident type, you will lose all information previously entered for this PER."

**Comment by gabycostales** [comment]
Add that warning and implemented the pop up
